# Generated by Django 3.2.16 on 2023-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_event',
            field=models.CharField(default='No Event Specified', max_length=50),
        ),
    ]
