# Generated by Django 3.2.16 on 2023-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_car_car_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='site_owner',
            field=models.BooleanField(default=False),
        ),
    ]
